# Generated by Django 5.0.1 on 2024-02-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='number',
            new_name='Bill_Number',
        ),
    ]
